#!/usr/bin/env ruby

# require project
require File.expand_path(File.join(File.dirname(__FILE__), 'lib', 'data_faker.rb'))

# if this file was executed directly
if __FILE__ == $0
  if ARGV[0] == 'reset'
    DataFaker.reset!
  else
    DataFaker.run! 
  end
end